apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: ocp-keycloak
  labels:
    app: ocp
spec:
  instances: 2
  extensions:
    - >-
      https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: false
  externalDatabase:
    enabled: true
  # keycloakDeploymentSpec:
  #   experimental:
  #     env:
  #       JDBC_PARAMS      
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: ocp-realm
  labels:
    app: ocp
spec:
  realm:
    id: ocp
    realm: ocp
    enabled: true
    displayName: OCP Realm
  instanceSelector:
    matchLabels:
      app: ocp 
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
stringData:
    POSTGRES_DATABASE: keycloak
    POSTGRES_EXTERNAL_ADDRESS: cockroachdb-public.cockroachdb.svc.cluster.local
    POSTGRES_EXTERNAL_PORT: "26257"
    # Strongly recommended to use <'Keycloak CR-Name'-postgresql>
    POSTGRES_HOST: ocp-realm-postgresql
    POSTGRES_PASSWORD: ${keycloak_username}
    # Required for AWS Backup functionality
    POSTGRES_SUPERUSER: "false"
    POSTGRES_USERNAME: ${keycloak_username}
    JDBC_PARAMS
type: Opaque
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    route-type: global    
  name: keycloak
spec:
  host: keycloak.${global_base_domain}
  port:
    targetPort: 8443
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: keycloak  