annotations:
  artifacthub.io/crds: |
    - kind: Gslb
      version: v1beta1
      name: gslb
      displayName: Gslb
      description: Gslb resource for global load balancing strategy configuration
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
apiVersion: v2
appVersion: v0.7.4
dependencies:
- name: coredns
  repository: https://coredns.github.io/helm
  version: 1.14.0
- name: etcd-operator
  repository: https://charts.helm.sh/stable
  version: 0.11.0
description: A Helm chart for Kubernetes Global Balancer
name: k8gb
type: application
version: v0.7.4
