isMultiAz: true

masterAddresses: yb-master-0.cluster1.yb-masters.yugabyte.svc.clusterset.local:7100,yb-master-0.cluster2.yb-masters.yugabyte.svc.clusterset.local:7100,yb-master-0.cluster3.yb-masters.yugabyte.svc.clusterset.local:7100

storage:
  master:
    size: 300Gi
    storageClass: "yugabyte"
  tserver:
    size: 80Gi
    storageClass: "yugabyte"

replicas:
  master: 1
  tserver: 3
  totalMasters: 3

resource:
  master:
    requests:
      cpu: 10
      memory: 22Gi
    limits:
      cpu: null
      memory: 22Gi 
  tserver:
    requests:
      cpu: 4
      memory: 4Gi
    limits:
      cpu: null
      memory: 4Gi       

tls:
  enabled: true

base_domain: ${global_base_domain}
cluster: ${cluster}
domainName: "clusterset.local"
tolerations:
  - key: "workload"
    operator: "Equal"
    value: "yugabyte"
    effect: "NoSchedule"
nodeSelector:
  workload: yugabyte

uid: ${uid}
guid: ${guid}  

serviceMonitor:
  enabled: true
  extraLabels:
    release: prom