{{- $root := . -}}
{{- range until (int .Values.replicas.tserver) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ (index $root.Values.Services 1).label }}-yugabyte-tls-cert-{{ . }}
spec:
  # Secret names are always required.
  secretName: {{ (index $root.Values.Services 1).label }}-yugabyte-tls-cert-{{ . }}
  commonName: {{ (index $root.Values.Services 1).label }}-{{ . }}.{{ $root.Values.cluster }}.{{ (index $root.Values.Services 1).name }}.{{ $root.Release.Namespace }}.svc.clusterset.local
  usages:
    - server auth
    - client auth  
  dnsNames:
  - {{ (index $root.Values.Services 1).label }}-{{ . }}.{{ $root.Values.cluster }}.{{ (index $root.Values.Services 1).name }}.{{ $root.Release.Namespace }}.svc.clusterset.local
  - {{ (index $root.Values.Services 1).label }}-{{ . }}.{{ (index $root.Values.Services 1).name }}.{{ $root.Release.Namespace }}.svc.cluster.local
  - {{ (index $root.Values.Services 1).label }}-{{ . }}.{{ (index $root.Values.Services 1).name }}.{{ $root.Release.Namespace }}.svc
  duration: 168h
  renewBefore: 1h
  issuerRef:
    name: vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
---    
{{- end }}    