{{ if .Values.route53.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-route53
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-route53
  template:
    metadata:
      labels:
        app: external-dns-route53
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: {{ .Values.externaldns.image }}
        args:
        - --source=crd
        - --domain-filter={{ .Values.k8gb.edgeDNSZone }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --annotation-filter=k8gb.absa.oss/dnstype=route53 # filter out only relevant DNSEntrypoints
        - --provider=aws
        - --txt-owner-id=k8gb-{{ .Values.route53.hostedZoneID }}-{{ .Values.k8gb.clusterGeoTag }}
        - --policy=sync # enable full synchronization including record removal
        - --log-level=debug # debug only
        - --managed-record-types=A,CNAME,NS
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          #fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
          #runAsUser: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
{{ end }}
